services:
  db:
    image: mysql:8.1
    container_name: mysql_app
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: myapp
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: "123456"
      DB_NAME: myapp
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:

