apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  type: NodePort  # para acesso via localhost
  selector:
    app: client
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
